# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WBh5yhMliOAx4RzA_yV2qSFpe5FxSUUK
"""

# This is Intr to Python 
print("Hello, Python Enthusiasts, Welcome Introduction to Python.")

a = 5
print(a)

"""
Hello Guys, 
How are you all doing? 
How do you feel about this class?
"""
# \n means new line

help("keywords")

# Rules of naming variables 
# It should not start with any numbers
# It should not have any gaps 
# Except of underscore _ any other signs should not be used in variable names

# Syntax Errors 
if (4 > 2):
  print("If 4 is greater than 2")

# Finding type of variables 
a = 6
b = 6.5 
c = "Sami"

print(type(a))
print(type(b))
print(type(c))

a_1 = 4 
print(a * c)

m = 4.5
n = 2
q = m * n 
print(q)

# Modulus Function 
"""
Anything getting divided by any specific number the leftout value or the remainder value is the modulus of it
"""
p = m % n 
print(p)

y = str("sam")
t = 5
print(y * t)

# Assigning Multiple Names to multiple variables
class_mate_1, class_mate_2, class_mate_3 = "Sameen", "Dibbo", "Irfan"
print(class_mate_1)
print(class_mate_2)
print(class_mate_3)

#Packing and Unpacking of variables
friends = ["Sameen", "Dibbo", "Irfan"]
class_mate_1, class_mate_2, class_mate_3 = friends
print(class_mate_1)
print(class_mate_2)
print(class_mate_3)

e = f = g = 'Python Class'

print(e)
print(f)
print(g)

# Global Variables 
x = "horrible teacher"

def teacher_rating():
  print("HAS sir is a " + x)

teacher_rating()

x = "horrible teacher"

def teacher_rating():
  global x
  x = "difficult teacher"

teacher_rating()
print("HAS sir is a " + x)

#Finding a random number between 1 to 10
#uniform is a representative for finding floating random numbers
import random as rd 

print(rd.uniform(103.45, 118.92))
print(rd.randrange(1, 10))

# String Positing 
a = "Hello, Students!"
print(a[10])

print(len(a))

#Loop through a string 
lecture_type = "Is it a fun class?"

print(len(lecture_type))

for x in lecture_type:
  print(x)

# String Slice
a = "Hello, class of Python!"
print(a[3:10])

print(a[3:])

print(a[:7])

print(a[:-3])

print(a[-3:])

print(a[-9:-4])

print(a.upper())

print(a.lower())

print(a.replace("P", "C"))

#Concatenation or Joining two strings
x = "Python is easy"
y = " if HAS sir doesn't teach"
print(x + y)

#String formatting with input
name = input("Enter Your name: ")
year = input("Enter Your University semester: ")
txt = "My Name is {0} and I am in my {1} semester."
print(txt.format(name, year))